"""Add description and recurrence fields to Task

Revision ID: 6a690adb172f
Revises: e218cf0aa955
Create Date: 2025-04-19 00:34:11.334392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a690adb172f'
down_revision = 'e218cf0aa955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('recurrence', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'recurrence')
    op.drop_column('task', 'description')
    # ### end Alembic commands ###
